FROM vertx/vertx3

ENV VERTICLE_HOME /src/main/java/verticles

ENV VERTICLE_NAME io.swagger.server.api.MainApiVerticle

COPY ./verticles $VERTICLE_HOME

ENTRYPOINT ["sh", "-c"]

CMD ["exec vertx run $VERTICLE_NAME -cp $VERTICLE_HOME/*"]